export AWS_DEFAULT_REGION="eu-north-1"
export PROJECT_S3_BUCKET="bob-csv-to-json-bucket"
export TF_VAR_state_bucket="bob-test-10101982-terraform-bucket"
export TF_VAR_project_name="csv-to-json-converter"
export TF_VAR_aws_region="${AWS_DEFAULT_REGION}"
